### ISSUE TITLE
Accessibility errors found in your template

### ISSUE THREAD

**Issue by wapyce** [vllur/newspaper#1]
The user @carlsonsantana validate your site template "https://vllur.github.io/newspaper/" and found these accessibility errors:
* Page https://vllur.github.io/newspaper/:
  * Issue *3611cb29-3c4d-42de-8fc2-b5146828c960*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G145.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 3:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #92949c.
    * **Selector**: `html > body > main > footer > span > a > b`
    * **Context**: `<b>vellur</b>`
  * Issue *3e74dbc3-8803-431a-83bf-4899d8fc9975*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > footer > span > a`
    * **Context**: `<a href="https://vllur.github.io/newspaper">
		<b>vellur</b>
		
		© 2018
	</a>`
  * Issue *a3624df9-885c-407d-a7e6-23e9d65e1410*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > div:nth-child(10) > a:nth-child(5)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/page/2/" class="page-item">»</a>`
  * Issue *ef1856f7-66d3-44cb-8cc7-2b5ab018f417*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > div:nth-child(10) > a:nth-child(4)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/page/3/" class="page-item">3</a>`
  * Issue *c27c9b59-683f-46f1-b65b-84c645bc538c*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > div:nth-child(10) > a:nth-child(3)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/page/2/" class="page-item">2</a>`
  * Issue *8bfda43d-7327-49f0-a1da-1cde645024c4*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > article:nth-child(9) > span > a:nth-child(3) > code`
    * **Context**: `<code class="highligher-rouge">page</code>`
  * Issue *5173d3b0-5406-45bb-aed6-6ac7e034bcf0*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > article:nth-child(9) > span > a:nth-child(2) > code`
    * **Context**: `<code class="highligher-rouge">sample</code>`
  * Issue *9952e30a-865a-48f7-a216-3038aa532396*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > article:nth-child(9) > span > a:nth-child(1) > code`
    * **Context**: `<code class="highligher-rouge">pinned</code>`
  * Issue *3ea94d32-40aa-4806-b958-481a66d1fe50*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.95:1. Recommendation: change text colour to #767676.
    * **Selector**: `html > body > main > article:nth-child(9) > time`
    * **Context**: `<time datetime="2018-09-03T00:00:00+00:00">03 Sep 2018</time>`
  * Issue *94625bab-146b-4844-8dd7-408989e7251e*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G145.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 3:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #92949c.
    * **Selector**: `html > body > main > article:nth-child(9) > h2 > a`
    * **Context**: `<a href="https://vllur.github.io/newspaper/Pinned-Page">Pinned Page</a>`
  * Issue *6f55c4fe-9609-4e0e-9c25-f7f547f38512*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > article:nth-child(8) > span > a:nth-child(2) > code`
    * **Context**: `<code class="highligher-rouge">page</code>`
  * Issue *785cf7a1-0489-4742-b037-24f98f51e7a6*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > article:nth-child(8) > span > a:nth-child(1) > code`
    * **Context**: `<code class="highligher-rouge">sample</code>`
  * Issue *b485cf0d-e16d-42e9-8ef5-c809dfdf16b9*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.95:1. Recommendation: change text colour to #767676.
    * **Selector**: `html > body > main > article:nth-child(8) > time`
    * **Context**: `<time datetime="2018-11-13T00:00:00+00:00">13 Nov 2018</time>`
  * Issue *bf8bd9db-f0da-4c87-a137-b5418b921be9*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G145.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 3:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #92949c.
    * **Selector**: `html > body > main > article:nth-child(8) > h2 > a`
    * **Context**: `<a href="https://vllur.github.io/newspaper/Sample-Page">Sample Page</a>`
  * Issue *9e26bfe1-5cf6-457c-b17c-498d4ce61838*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > div:nth-child(7) > a:nth-child(5)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/page/2/" class="page-item">»</a>`
  * Issue *e6c0649f-f9f8-4d73-b3a2-5fbdb1c6b9a7*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > div:nth-child(7) > a:nth-child(4)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/page/3/" class="page-item">3</a>`
  * Issue *0a507089-847a-4502-9f9f-a76f5b244f00*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > div:nth-child(7) > a:nth-child(3)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/page/2/" class="page-item">2</a>`
  * Issue *64be3afb-41f6-4be0-9f31-b952cc4f0124*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > article:nth-child(6) > span > a:nth-child(3) > code`
    * **Context**: `<code class="highligher-rouge">page</code>`
  * Issue *508c9933-c138-4be1-abbe-25bbbc749c2e*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > article:nth-child(6) > span > a:nth-child(2) > code`
    * **Context**: `<code class="highligher-rouge">sample</code>`
  * Issue *ebd84f87-cfd3-4ff1-b5c8-9e8f5386a147*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > article:nth-child(6) > span > a:nth-child(1) > code`
    * **Context**: `<code class="highligher-rouge">pinned</code>`
  * Issue *0a65bc60-35c0-4f3d-abb3-51f874e511b4*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G145.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 3:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #92949c.
    * **Selector**: `html > body > main > article:nth-child(6) > h4 > a`
    * **Context**: `<a href="https://vllur.github.io/newspaper/Pinned-Page">Pinned Page</a>`
  * Issue *8cfcf3c8-45b5-4037-9cdd-eab66305a835*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > nav:nth-child(4) > a`
    * **Context**: `<a href="https://vllur.github.io/newspaper">newspaper</a>`
  * Issue *00d29d56-bdcc-4650-a21b-70a9119f8df2*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > nav:nth-child(1) > a:nth-child(4)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/atom.xml">RSS</a>`
  * Issue *9b408ca8-5c68-4b06-82f1-9b21dbc84b9a*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > nav:nth-child(1) > a:nth-child(3)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/tag">Tags</a>`
  * Issue *8e3eb4c2-5894-4f03-ae2e-c179d153411a*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > nav:nth-child(1) > a:nth-child(2)`
    * **Context**: `<a href="https://vllur.github.io/newspaper/archive">Archive</a>`
  * Issue *6206767e-de01-4cd6-94ee-58e64dd1fdc1*:
    * **Type**: Error
    * **Code**: WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
    * **Message**: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.55:1. Recommendation: change text colour to #74767e.
    * **Selector**: `html > body > main > nav:nth-child(1) > a:nth-child(1)`
    * **Context**: `<a href="https://vllur.github.io/newspaper">Home</a>`

You can check these accessibility errors using [pa11y](https://github.com/pa11y/pa11y).
You can view the [full validation results in our website](https://wapyce.herokuapp.com/validation/validations/38a9be65-5335-4d4c-851e-06c7bb8fdbaf/).

**Comment by vllur** [comment]
Fixed by 9cf489eb69711f0567a85f38af2daa803a33dc20.
